spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 784446908563-mecj1ijjk02b1064karovm690fedar97.apps.googleusercontent.com
            client-secret: ${OAUTH2_SECRET_GOOGLE}
            redirect-uri: http://localhost:5173/oauth2/login
#            redirect-uri: https://mokkoji.online/oauth2/login/google
            authorization-grant-type: authorization_code
            scope: email, profile


          naver:
            client-id: Y_veSn1KXI8bYwTv29AA
            client-secret: ${OAUTH2_SECRET_NAVER}
            redirect-uri: https://mokkoji.online/oauth2/login
#            redirect-uri: https://mokkoji.online/oauth2/login/naver
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          #          kakao:
          #            authorization_uri: https://kauth.kakao.com/oauth/authorize
          #            token_uri: https://kauth.kakao.com/oauth/token
          #            user-info-uri: https://kapi.kakao.com/v2/user/me
          #            user_name_attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response