spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mokkoji
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  data:
    web:
      pageable:
        default-page-size: 10 #이렇게 설정가능
        max-page-size: 2000
        one-indexed-parameters: true #인덱스가 1인 파라미터부터 시작. 근데 이건 페이징이 안됨

    # redis
    redis:
      host: localhost
      port: 6379

  #application 프로필 등록
  profiles:
    include: oauth, jwt, s3


# OpenVidu
OPENVIDU_URL: http://localhost:4443/
OPENVIDU_SECRET: MOKKOJI_SECRET

# server
server:
  port: '5000'
  ssl:
    enabled: 'false'

# url:

logging:
  level:
   org.hibernate.SQL: trace
# org.hibernate.type: trace