spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: Y_veSn1KXI8bYwTv29AA
            client-secret: #시크릿 키 넣기
            redirect-uri: "http://localhost:5173/oauth2/login"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response