spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test   #경로 추기
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect


  data:
    web:
      pageable:
        default-page-size: 10 #이렇게 설정가능
        max-page-size: 2000
        one-indexed-parameters: true #인덱스가 1인 파라미터부터 시작. 근데 이건 페이징이 안됨

    # redis
    redis:
      host: localhost
      port: 6379

  
#      url:
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace


cloud:
  aws:
    s3:
      bucket: mokkoji-bucket # 버킷명
    credentials:
      access-key: AKIAVHLP3OU6SLLAJDH2
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

