spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 784446908563-mecj1ijjk02b1064karovm690fedar97.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            scope: email, profile

          #          kakao:
          #            client-id: {client-id(Rest Api key)}
          #            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
          #            client-authentication-method: POST
          #            authorization-grant-type: authorization_code
          #            scope: profile_nickname, profile_image, account_email

          naver:
            client-id: Y_veSn1KXI8bYwTv29AA
            client-secret: ZrcTvy2t84
            redirect-uri: "http://localhost:5173/oauth2/login"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          #          kakao:
          #            authorization_uri: https://kauth.kakao.com/oauth/authorize
          #            token_uri: https://kauth.kakao.com/oauth/token
          #            user-info-uri: https://kapi.kakao.com/v2/user/me
          #            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response