spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 784446908563-mecj1ijjk02b1064karovm690fedar97.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          #naver에선 spring security 공식지원 X
          naver:
            client-id: Y_veSn1KXI8bYwTv29AA
            client-secret: ZrcTvy2t84
            redirect-uri: 'http://localhost:8080/login/oauth2/code/naver'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - profile_image
            client-name: Naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



