version: '3'
services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:backend-latest
    ports:
      - '8080:8080'
    env_file:
      - ./.env
    # opencv mount
    volumes:
      - /home/ubuntu/opencv:/usr/src/app/result
